admin.users.getAll=SELECT * FROM users

admin.events.getAll=SELECT * FROM events

admin.vendor.approve=UPDATE vendors SET approved = true WHERE id = ?

admin.event.approve=UPDATE events SET status = 'APPROVED' WHERE id = ?

user.events.search=SELECT id, event_name, event_location, event_date, price, latitude, longitude, event_description, status FROM events WHERE LOWER(event_name) LIKE LOWER(CONCAT('%', ?, '%'))

user.events.searchdetail=SELECT * FROM events WHERE LOWER(event_name) LIKE LOWER(CONCAT('%', ?, '%'))